fix:#463 notification bug
idurar/erp-crm pull request #472
Opened 2023-09-06 21:57 UTC by Sinharitik589

## Description

Please provide a brief description of the changes or additions made in this pull request.

## Related Issues

#463 

## Screenshots (if applicable)
Before-

![ezgif com-video-to-gif (5)](https://github.com/idurar/idurar-erp-crm/assets/67551927/44b464c0-d6f4-49d3-959e-1bb2afae7c51)

After-

![ezgif com-video-to-gif (6)](https://github.com/idurar/idurar-erp-crm/assets/67551927/68f72379-bb51-43e2-b8f4-7d0796613474)

If your changes include visual updates, it would be helpful to provide screenshots of the before and after.

## Checklist

- [x] I have tested these changes
- [ ] I have updated the relevant documentation
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the codebase
- [x] My changes generate no new warnings or errors
- [x] The title of my pull request is clear and descriptive

2023-09-07 17:56 UTC, polymahh approved these changes

2023-09-07 23:11 UTC, salahlalami approved these changes

2023-09-08 00:06 UTC, polymahh requested changes
@salahlalami this PR has some commits that were directly merged to master , is there no problem if they show in dev ??

2023-09-13 09:53 UTC, polymahh approved these changes

2023-09-13 09:53 UTC, merged