[FIX] paymentInvoice creation and invoice status
idurar/erp-crm pull request #486
Opened 2023-09-08 11:01 UTC by Ando22

## Description
There's an error in creating the payment invoice. the payload of the API needs to be validated before communicating to the DB. this impacts updating the payment status of the related invoice.

## Related Issues
This PR tackling this issue #271 

## Steps to Test
Create a Payment Invoice for an Invoice, based on Invoice Number. try to pay some of the item, to get `partial` status, and pay all the item to get `paid` of Invoice payment status

## Screenshots (if applicable)
<img width="905" alt="Screen Shot 2023-09-08 at 18 00 02" src="https://github.com/idurar/idurar-erp-crm/assets/38315094/7415fee8-2e72-41c8-b43b-7b2d47f16b86">

## Checklist
- [ ] I have tested these changes

2023-09-08 11:09 UTC, salahlalami requested changes

2023-09-08 11:09 UTC, salahlalami commented on frontend/.env
> +REACT_APP_BACKEND_SERVER="http://localhost:8888"
revert env file

2023-09-08 19:14 UTC, salahlalami commented
@polymahh so it doesn't work

2023-09-11 11:41 UTC, Ando22 commented on frontend/.env
> +REACT_APP_BACKEND_SERVER="http://localhost:8888"
done

2023-09-14 19:36 UTC, polymahh commented
@Ando22 there is no need for this PR if we are removing "add new payment"

2023-09-17 23:47 UTC, closed without merging