Fix the bug for download payment receipt which returns invoice pdf instead of payment receipt 489
idurar/erp-crm pull request #492
Opened 2023-09-08 21:22 UTC by onfranciis

## Description
- Fixed payment/invoice/edit from breaking
- Updated pug to support Payment Invoice

## Related Issues
- #489 

## Steps to Test
- Go to 'payment/invoice'
- Click on 'download'

## Checklist

- [x] I have tested these changes
- [x] I have updated the relevant documentation
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the codebase
- [x] My changes generate no new warnings or errors
- [x] The title of my pull request is clear and descriptive

2023-09-08 22:39 UTC, salahlalami requested changes

2023-09-08 22:39 UTC, salahlalami commented on views/pdf/PaymentInvoice.pug
>        .col.col-24
The Receipt should show only invoice number , date , invoice total (small font)
Total paid (Big Font)
There is no items list

2023-09-14 23:29 UTC, salahlalami approved these changes

2023-09-15 11:27 UTC, polymahh approved these changes
tested

![image](https://github.com/idurar/erp-crm/assets/15654652/599f8965-f0f3-4df1-9891-2890db1a245b)

2023-09-15 11:49 UTC, merged