fix: clicking on update redirects to read page
idurar/erp-crm pull request #508
Opened 2023-09-11 14:56 UTC by polymahh

## Description

after clicking on update in erp module the update page stays open 
now it should redirects to entity/read/id

## Related Issues
no issue

2023-09-11 15:14 UTC, salahlalami requested changes

2023-09-11 15:14 UTC, salahlalami commented on frontend/src/modules/ErpPanelModule/UpdateItem.jsx
> -      updatePanel.close();
move this here : 
history.push(`/${entity.toLowerCase()}/read/${id}`);

2023-09-11 17:24 UTC, salahlalami approved these changes

2023-09-12 10:27 UTC, Ando22 approved these changes

2023-09-12 13:34 UTC, merged