[Draft][FEATURE] Create offer frontend CRUD
idurar/erp-crm pull request #537
Opened 2023-09-16 11:13 UTC by Ando22

## Description
creating a frontend offer feature for users to create offer requests for an Item.

this PR will be merged when this [issue](https://github.com/idurar/erp-crm/issues/389) is fixed 

## Related Issues
This PR is related to this [issue](https://github.com/idurar/erp-crm/issues/390). 

## Screenshots (if applicable)

## Checklist

- [ ] I have tested these changes
- [ ] I have made corresponding changes to the codebase

2023-09-16 12:31 UTC, salahlalami requested changes

2023-09-16 12:31 UTC, salahlalami commented on frontend/.env
> +REACT_APP_BACKEND_SERVER="http://localhost:8888"
add .env to .gitignore

2023-09-17 14:40 UTC, Ando22 commented on frontend/.env
> +REACT_APP_BACKEND_SERVER="http://localhost:8888"
oke on it

2023-09-17 19:59 UTC, polymahh approved these changes
seems good to me

2023-09-17 21:00 UTC, salahlalami approved these changes

2023-09-18 09:19 UTC, Ando22 commented
@polymahh @salahlalami thank you guys, but i will merge this PR after this PR is merged

https://github.com/idurar/erp-crm/pull/552

2023-09-18 20:01 UTC, merged