feat: add tax CRUD
idurar/erp-crm pull request #568
Opened 2023-09-24 15:14 UTC by TanyaLagodich

## Description

Added tax CRUD on backend

## Related Issues

Issue: [
<img width="978" alt="Снимок экрана 2023-09-24 в 19 10 40" src="https://github.com/idurar/erp-crm/assets/38503908/33082ac5-3091-425f-a113-c9756750f99a">
](https://github.com/idurar/erp-crm/issues/544)

## Steps to Test

Provide steps on how to test the changes introduced in this pull request.

## Screenshots (if applicable)

I have tested it on Postman
Can create new tax with TaxName (string) and TaxValue (number).
Also can provide some other fields such as `isDefault`, `created`, `removed` and `enabled`

## Checklist

- [X] I have tested these changes
- [X] I have updated the relevant documentation
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the codebase
- [X] My changes generate no new warnings or errors
- [X] The title of my pull request is clear and descriptive

2023-09-24 23:49 UTC, salahlalami requested changes

2023-09-25 06:48 UTC, TanyaLagodich commented on backend/controllers/appControllers/taxController.js
> +module.exports = createCRUDController('Tax');
Thanks for your feedback!

I've done it. Please, check it

Also I am thinking may be we should add some validation? As I understand, client will always send full json of tax? I mean with enabled field, right? So if it won't, there is might be some issues

And also maybe when `if the new or update is isDefault:true , we should update all other to be isDefault:false` we should check enabled field? in order to do not just the first tax, but the first and enabled tax?

If it's okey, I will do it quickly

2023-09-26 12:53 UTC, salahlalami requested changes

2023-09-26 12:53 UTC, salahlalami commented on backend/controllers/appControllers/taxController.js
> +        const result = await new Model({ isDefault, ...rest }).save();
use same instruction as crudmiddleware :     const result = await new Model(req.body).save();

2023-09-26 12:53 UTC, salahlalami commented on backend/controllers/appControllers/taxController.js
> +module.exports = createCRUDController('Tax');
@TanyaLagodich yes , sure .
just make test to see if it work

2023-09-27 06:09 UTC, TanyaLagodich commented on backend/controllers/appControllers/taxController.js
> +        const result = await new Model({ isDefault, ...rest }).save();
Done!

2023-09-27 06:09 UTC, TanyaLagodich commented on backend/controllers/appControllers/taxController.js
> +module.exports = createCRUDController('Tax');
Ok! I've done it. Tests with screenshots in description of PR

2023-09-30 19:04 UTC, salahlalami approved these changes
@TanyaLagodich Thank you

2023-09-30 19:04 UTC, merged